#!/usr/bin/env zsh

CFG_DIR=$1

homelink() {
	rm -f $1
	ln -s $CFG_DIR/$1
}

homelink .agignore
homelink .gdbinit
homelink .gtkrc-2.0
#homelink .nvidia-settings-rc
homelink .profile
homelink .xinitrc
homelink .zprofile
homelink .zshenv
homelink .zshrc
homelink .config
homelink .Xresources
